package net.java21.blog.backend.common.error;

import org.springframework.http.HttpStatus;

/**
 * 공통 오류 코드. 값(name)은 응답의 {@code header.resultCode}이며 한번 정하면 바꾸지 않는다(FR-154).
 * 기능별 코드(POST_NOT_FOUND 등)는 각 기능을 만들 때 contracts/api.md 표에 맞춰 더한다.
 */
public enum ErrorCode {

    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    ORIGIN_NOT_ALLOWED(HttpStatus.FORBIDDEN),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    TOO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    // 001 인증·블로그·글 (contracts/api.md 오류 코드 표)
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    REFRESH_INVALID(HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED(HttpStatus.LOCKED),
    CURRENT_PASSWORD_MISMATCH(HttpStatus.BAD_REQUEST),
    EMAIL_TAKEN(HttpStatus.CONFLICT),
    HANDLE_TAKEN(HttpStatus.CONFLICT),
    BLOG_LIMIT_EXCEEDED(HttpStatus.CONFLICT),
    LAST_BLOG_CANNOT_BE_DELETED(HttpStatus.CONFLICT),
    POST_NOT_PUBLISHED(HttpStatus.CONFLICT),
    HANDLE_RESERVED(HttpStatus.UNPROCESSABLE_CONTENT),
    HANDLE_INVALID(HttpStatus.UNPROCESSABLE_CONTENT),
    TERMS_VERSION_OUTDATED(HttpStatus.UNPROCESSABLE_CONTENT),
    POST_CONTENT_EMPTY(HttpStatus.UNPROCESSABLE_CONTENT),
    POST_NOT_IN_TRASH(HttpStatus.UNPROCESSABLE_CONTENT),
    CATEGORY_DEPTH_EXCEEDED(HttpStatus.UNPROCESSABLE_CONTENT),
    TAG_LIMIT_EXCEEDED(HttpStatus.UNPROCESSABLE_CONTENT),
    BLOG_NOT_FOUND(HttpStatus.NOT_FOUND),
    POST_NOT_FOUND(HttpStatus.NOT_FOUND),
    DRAFT_NOT_FOUND(HttpStatus.NOT_FOUND),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND),
    CATEGORY_NAME_TAKEN(HttpStatus.CONFLICT),

    // 001 계정 설정 (Phase 4)
    PASSWORD_RESET_TOKEN_INVALID(HttpStatus.BAD_REQUEST),

    // 001 댓글 (US3, FR-027~029)
    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    REPLY_DEPTH_EXCEEDED(HttpStatus.UNPROCESSABLE_CONTENT),
    COMMENTS_DISABLED(HttpStatus.UNPROCESSABLE_CONTENT),


    // 001 이미지 (US4, FR-038·039, FR-130~132, FR-156)
    MEDIA_NOT_FOUND(HttpStatus.NOT_FOUND),
    MEDIA_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE),
    MEDIA_TYPE_NOT_ALLOWED(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    MEDIA_TEMP_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    THUMBNAIL_SIZE_NOT_ALLOWED(HttpStatus.BAD_REQUEST),

    // 002 구독과 탐색 (002 contracts/api.md 오류 코드 표)
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    CANNOT_SUBSCRIBE_OWN_BLOG(HttpStatus.UNPROCESSABLE_CONTENT),

    // 003 포털 (003 contracts/api.md 오류 코드 표)
    TOPIC_NOT_FOUND(HttpStatus.NOT_FOUND),
    TOPIC_NOT_SELECTABLE(HttpStatus.UNPROCESSABLE_CONTENT),
    TOPIC_SLUG_TAKEN(HttpStatus.CONFLICT),
    TOPIC_DEPTH_EXCEEDED(HttpStatus.UNPROCESSABLE_CONTENT),
    CURATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    CURATION_LIMIT_EXCEEDED(HttpStatus.CONFLICT),
    POST_NOT_PORTAL_ELIGIBLE(HttpStatus.UNPROCESSABLE_CONTENT),
    PORTAL_EXCLUSION_NOT_FOUND(HttpStatus.NOT_FOUND),
    SETTING_NOT_FOUND(HttpStatus.NOT_FOUND),

    // 001 contracts 릴리스 노트(003에서 구현, 001 결정 8번)
    RELEASE_NOTE_NOT_FOUND(HttpStatus.NOT_FOUND),
    RELEASE_NOTE_VERSION_TAKEN(HttpStatus.CONFLICT),
    RELEASE_NOTE_REVISION_CONFLICT(HttpStatus.CONFLICT),
    RELEASE_NOTE_ONCE_PUBLISHED(HttpStatus.CONFLICT),
    RELEASE_NOTE_VERSION_LOCKED(HttpStatus.UNPROCESSABLE_CONTENT),

    // 004 블로그 꾸미기와 글 옵션 (004 contracts/api.md 오류 코드 표)
    POST_PASSWORD_MISMATCH(HttpStatus.BAD_REQUEST),
    POST_LOCKED(HttpStatus.FORBIDDEN),
    PASSWORD_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    SCHEDULE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_CONTENT),
    POST_NOT_SCHEDULED(HttpStatus.CONFLICT),
    GUEST_PASSWORD_MISMATCH(HttpStatus.FORBIDDEN),
    GUESTBOOK_DISABLED(HttpStatus.NOT_FOUND),
    GUESTBOOK_ENTRY_NOT_FOUND(HttpStatus.NOT_FOUND),
    EXPORT_LIMIT_EXCEEDED(HttpStatus.CONFLICT),
    EXPORT_NOT_FOUND(HttpStatus.NOT_FOUND),
    CANNOT_BLOCK_SELF(HttpStatus.UNPROCESSABLE_CONTENT),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    BLOCK_NOT_FOUND(HttpStatus.NOT_FOUND);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
